import json
import os

TRANSLATIONS_DIR = r"c:\Users\Roger\Documents\AA PROJECTS\1 SIH FE\src\translations"

# Load base English
with open(os.path.join(TRANSLATIONS_DIR, "en.json"), "r", encoding="utf-8") as f:
    en = json.load(f)

# Load existing Marathi and Odia
with open(os.path.join(TRANSLATIONS_DIR, "mr.json"), "r", encoding="utf-8") as f:
    mr = json.load(f)

with open(os.path.join(TRANSLATIONS_DIR, "or.json"), "r", encoding="utf-8") as f:
    od = json.load(f)

MR_OVERRIDES = {
    "shareEligibilityTitle": "तुमची पात्रता शेअर करा",
    "shareEligibilitySubtitle": "तुम्ही पात्र असलेल्या सरकारी योजनांचा सारांश पाठवा.",
    "copyLink": "दुवा कॉपी करा",
    "downloadPdf": "पीडीएफ डाउनलोड करा",
    "linkCopiedToast": "शेअर करण्यायोग्य दुवा क्लिपबोर्डवर कॉपी केला!",
    "platformOverview": "प्लॅटफॉर्म आढावा",
    "totalUsers": "एकूण वापरकर्ते",
    "totalBusinesses": "एकूण व्यवसाय",
    "totalApplications": "एकूण अर्ज",
    "pendingApplications": "प्रलंबित अर्ज",
    "approvedApplications": "मंजूर अर्ज",
    "rejectedApplications": "नाकारलेले अर्ज",
    "applicationsTrend": "अर्ज ट्रेंड",
    "applicationsByCategory": "वर्गवारीनुसार अर्ज",
    "topAppliedSchemes": "सर्वाधिक अर्ज केलेल्या योजना",
    "reviewVerdict": "पुनरावलोकन निर्णय",
    "rejectionReasonPrompt": "नकार कारण (आवश्यक)",
    "approveApplication": "अर्ज मंजूर करा",
    "rejectApplication": "अर्ज नाकारा",
    "markReviewLater": "नंतर पुनरावलोकन करा",
    "savedItems": "जतन केलेल्या बाबी",
    "reviewNow": "आता पुनरावलोकन करा",
    "addNewScheme": "नवीन योजना जोडा",
    "editScheme": "योजना संपादित करा",
    "saveScheme": "योजना जतन करा",
    "deleteSchemeConfirm": "तुम्हाला खात्री आहे की तुम्ही ही योजना हटवू इच्छिता?",
    "searchLanguage": "भाषा शोधा...",
    "switchProfileContext": "प्रोफाइल संदर्भ बदला",
    "youContext": "{name} (वैयक्तिक)",
    "personalContextTitle": "वैयक्तिक प्रोफाइल",
    "personalDashboardDesc": "तुमच्या प्रोफाइलसाठी तयार केलेल्या वैयक्तिक नागरिक सबसिडी, कल्याणकारी कार्यक्रम आणि थेट लाभ योजना.",
    "businessDashboardDesc": "तुमच्या व्यवसायासाठी शोधलेल्या एंटरप्राइझ सबसिडी, भांडवली सहाय्य आणि उद्योग-विशिष्ट अनुदाने.",
    "eligibleSchemesDiscovered": "पात्र योजना शोधल्या",
    "noMatchingSchemesFound": "कोणतीही जुळणारी योजना सापडली नाही",
    "noSchemesFoundDesc": "तुमची शोध क्वेरी बदलून, फिल्टर साफ करून किंवा प्रोफाइल संदर्भ बदलून पहा.",
    "resetFilters": "फिल्टर रीसेट करा",
    "clear": "साफ करा",
    "urgentDeadlineDesc": "या योजनेसाठी अर्ज लवकरच बंद होत आहेत ({deadline}). वेळेत छाननीसाठी लवकर सादर करा.",
    "businessApplication": "व्यवसाय अर्ज",
    "personalApplication": "वैयक्तिक अर्ज",
    "businessContext": "व्यवसाय संदर्भ",
    "selectRegisteredEnterprise": "नोंदणीकृत एंटरप्राइझ निवडा",
    "applyingAsIndividual": "वैयक्तिक नागरिक म्हणून अर्ज करत आहे",
    "personal": "वैयक्तिक",
    "business": "व्यवसाय",
    "ageGender": "वय आणि लिंग",
    "stateCategory": "राज्य आणि प्रवर्ग",
    "annualIncome": "वार्षिक उत्पन्न",
    "businessDetails": "व्यवसाय तपशील",
    "legalName": "कायदेशीर नाव",
    "turnoverSector": "उलाढाल आणि क्षेत्र",
    "bankName": "बँकेचे नाव",
    "accountNumber": "खाते क्रमांक",
    "ifscCode": "आयएफएससी कोड",
    "cultivableLandHolding": "एकूण लागवडीयोग्य जमीन (हेक्टरमध्ये)",
    "requiredCreditAmount": "आवश्यक कर्ज रक्कम (₹)",
    "uploadDocumentProof": "आवश्यक कागदपत्र पुरावा अपलोड करा (PDF / इमेज)",
    "clickToReplaceDocs": "बदलण्यासाठी किंवा अतिरिक्त फाइल्स जोडण्यासाठी क्लिक करा",
    "appReceivedRefId": "तुमचा अर्ज या संदर्भ क्रमांकासह प्राप्त झाला आहे:",
    "trackInMyApplications": "माझे अर्ज विभागात ट्रॅक करा",
    "returnToDashboard": "डॅशबोर्डवर परत जा",
    "myAppsSubtitle": "तुमच्या सर्व सरकारी योजना अर्जांचा रिअल-टाइम मागोवा घ्या",
    "searchApplications": "अर्ज शोधा...",
    "allApplicationsTab": "सर्व अर्ज ({count})",
    "personalTab": "वैयक्तिक ({count})",
    "businessTab": "व्यवसाय ({count})",
    "noApplicationsFound": "कोणतेही अर्ज आढळले नाहीत",
    "noAppsMatchQuery": "तुमच्या शोध क्वेरीशी कोणतेही अर्ज जुळत नाहीत.",
    "noAppsInCat": "तुम्ही या प्रवर्गात अद्याप कोणतेही अर्ज सादर केलेले नाहीत.",
    "appRegisteredUnder": "{category} उपक्रमांतर्गत नोंदणीकृत अर्ज.",
    "appTimelineVerification": "अर्ज टाइमलाइन आणि पडताळणी",
    "state": "राज्य",
    "close": "बंद करा",
    "notAdded": "जोडले नाही",
    "udyamRegNumber": "उद्यम नोंदणी क्र.",
    "addAnotherBusiness": "दुसरा व्यवसाय जोडा",
    "addAnotherBusinessDesc": "उद्योग-विशिष्ट सबसिडी शोधण्यासाठी अतिरिक्त एंटरप्राइझ प्रोफाइल नोंदणी करा.",
    "confirmDelete": "हटवण्याची पुष्टी करा",
    "deleteBusinessConfirm": "तुम्हाला खात्री आहे की तुम्ही हे व्यवसाय प्रोफाइल हटवू इच्छिता? संबंधित अर्ज तुमच्या इतिहासात राहतील.",
    "enterAccurateDetailsBiz": "पात्र व्यवसाय सबसिडी आणि अनुदाने शोधण्यासाठी अचूक तपशील प्रविष्ट करा.",
    "basicInformation": "१. मूलभूत माहिती",
    "registrationsIdentifiers": "२. नोंदणी आणि ओळख क्रमांक",
    "operationalContactDetails": "३. कार्य आणि संपर्क तपशील",
    "businessAddress": "व्यवसाय पत्ता",
    "contactPhone": "संपर्क फोन",
    "contactEmail": "संपर्क ईमेल",
    "bookmarksSubtitle": "त्वरित प्रवेशासाठी तुमचे जतन केलेले सरकारी कार्यक्रम आणि आर्थिक सबसिडी",
    "noBookmarksYet": "अद्याप कोणतेही बुकमार्क नाहीत",
    "noBookmarksDesc": "तुम्ही कोणत्याही योजना बुकमार्क केलेल्या नाहीत. डॅशबोर्डवरील उपलब्ध योजना ब्राउझ करा आणि जतन करण्यासाठी स्टार आयकॉनवर क्लिक करा.",
    "browseSchemes": "योजना ब्राउझ करा",
    "update": "अपडेट",
    "unread": "न वाचलेले",
    "updateDocument": "कागदपत्र अपडेट करा",
    "notificationsSubtitle": "तुमच्या अर्ज पुनरावलोकन आणि नवीन सरकारी योजनांच्या प्रकाशनांवर अपडेट रहा",
    "noNotifications": "कोणत्याही सूचना नाहीत",
    "allCaughtUp": "सर्व सूचना वाचल्या आहेत!",
    "citizenId": "नागरिक आयडी",
    "profileCompletedPercent": "{percent}% प्रोफाइल पूर्ण",
    "cancelEdit": "संपादन रद्द करा",
    "editProfile": "प्रोफाइल संपादित करा",
    "age": "वय",
    "saveChanges": "बदल जतन करा",
    "linkedVerified": "लिंक केलेले आणि पडताळलेले",
    "verificationDocuments": "पडताळणी कागदपत्रे",
    "notUploadedRequired": "अपलोड केलेले नाही (काही योजनांसाठी आवश्यक)",
    "uploaded": "अपलोड केले",
    "uploadProof": "पुरावा अपलोड करा",
    "updateBankDetails": "बँक तपशील अपडेट करा",
    "saveBankDetails": "बँक तपशील जतन करा",
    "applicantProfile": "अर्जदार प्रोफाइल",
    "enterpriseProfile": "एंटरप्राइझ प्रोफाइल",
    "verifiedResident": "पडताळलेला रहिवासी",
    "eligibleSchemesTitle": "पात्र योजना ({count})",
    "adminOverviewSubtitle": "योजना नोंदणी आणि प्रलंबित विभागीय निर्णयांसाठी कार्यकारी डॅशबोर्ड",
    "monthlyIntakeSubtitle": "वैयक्तिक आणि व्यवसाय योजनांमधील मासिक वितरण",
    "sectorShareBreakdown": "क्षेत्रनिहाय हिस्सा विश्लेषण",
    "total": "एकूण",
    "estVolume": "अंदाजे प्रमाण",
    "applicantsCount": "{count} अर्जदार",
    "searchAdminPlaceholder": "अर्ज आयडी, वापरकर्ता किंवा योजनेनुसार शोधा...",
    "status": "स्थिती",
    "allStatuses": "सर्व स्थिती",
    "fromDate": "या तारखेपासून",
    "toDate": "या तारखेपर्यंत",
    "reset": "रीसेट",
    "appId": "अर्ज आयडी",
    "applicant": "अर्जदार",
    "scheme": "योजना",
    "entity": "घटक",
    "action": "कृती",
    "noAppsMatchFilters": "सक्रिय फिल्टर्सशी कोणतेही अर्ज जुळत नाहीत.",
    "individual": "वैयक्तिक",
    "reviewApplication": "अर्ज पुनरावलोकन",
    "targetGovInitiative": "लक्षित सरकारी उपक्रम",
    "finalizeVerdictSubtitle": "पडताळणी निर्णय अंतिम करा किंवा पुढील पुनरावलोकनासाठी ठेवा.",
    "rejectionNotesPlaceholder": "नाकारल्यास अनिवार्य कारण किंवा अंतर्गत टिप्पण्या प्रविष्ट करा...",
    "noAppsInReviewLater": "नंतर पुनरावलोकन रांगेत कोणतेही अर्ज नाहीत",
    "noAppsInReviewLaterDesc": "अर्जांचे पुनरावलोकन करताना, तुम्ही नंतरच्या पाठपुराव्यासाठी बाबी येथे रांगेत ठेवू शकता.",
    "remove": "काढा",
    "queuedOn": "रांगेत जोडले",
    "auditStage": "ऑडिट टप्पा",
    "searchSchemesPlaceholder": "शीर्षक किंवा मंत्रालयानुसार योजना शोधा...",
    "active": "सक्रिय",
    "enterpriseScheme": "एंटरप्राइझ योजना",
    "citizenScheme": "नागरिक योजना",
    "alwaysOpen": "नेहमी सुरू",
    "confirmDeleteScheme": "योजना हटवण्याची पुष्टी करा",
    "deleteSchemeConfirmDesc": "तुम्हाला खात्री आहे की तुम्ही ही योजना सक्रिय निर्देशिकेतून काढू इच्छिता? आधीच सादर केलेले अर्ज सुरक्षित राहतील.",
    "configureEligibilitySubtitle": "पात्रता निकष आणि प्रकाशन मापदंड कॉन्फिगर करा",
    "schemeNameLabel": "योजनेचे नाव",
    "ministryDepartment": "मंत्रालय / विभाग",
    "description": "वर्णन",
    "descriptionPlaceholder": "योजनेचे फायदे आणि पात्रतेचे सर्वसमावेशक वर्णन...",
    "benefitHeadline": "फायदा शीर्षक (उदा. ₹६,००० / वर्ष)",
    "benefitDetail": "फायदा तपशील (उदा. थेट लाभ हस्तांतरण)",
    "eligibilityOperations": "२. पात्रता आणि कामकाज",
    "ageRange": "वयोगट (किमान - कमाल)",
    "maxAnnualIncome": "कमाल वार्षिक उत्पन्न",
    "applicationDeadline": "अर्जाची अंतिम मुदत",
    "isBusinessSchemeToggleLabel": "ही एक व्यवसाय / एंटरप्राइझ योजना आहे (एमएसएमई व व्यवसायांसाठी उपलब्ध)",
    "adminLoginSubtitle": "केंद्रीकृत प्रशासक पोर्टलवर प्रवेश करा",
    "authenticating": "प्रमाणीकरण होत आहे...",
    "asPerOfficialDocs": "अधिकृत कागदपत्रांनुसार",
    "mobilePlaceholder": "१०-अंकी मोबाइल",
    "min8Chars": "किमान ८ वर्ण",
    "slide1_prefix": "प्रत्येक",
    "slide1_main": "नागरिकासाठी.",
    "slide1_desc": "तुमच्यासाठी संबंधित सरकारी योजना आणि लाभ एकाच ठिकाणी शोधा.",
    "slide2_prefix": "प्रत्येक",
    "slide2_main": "विद्यार्थ्यासाठी.",
    "slide2_desc": "तुम्हाला पुढे जाण्यास मदत करण्यासाठी डिझाइन केलेल्या शिष्यवृत्ती आणि शिक्षण सहाय्य शोधा.",
    "slide3_prefix": "प्रत्येक",
    "slide3_main": "शेतकऱ्यासाठी.",
    "slide3_desc": "तुमच्या उपजीविकेसाठी तयार केलेली कृषी मदत, आर्थिक सहाय्य आणि योजना शोधा.",
    "slide4_prefix": "प्रत्येक",
    "slide4_main": "महिलांसाठी.",
    "slide4_desc": "तुम्हाला प्रगती करण्यास मदत करणारे फायदे, आर्थिक सहाय्य आणि संधी शोधा.",
    "slide5_prefix": "प्रत्येक",
    "slide5_main": "उद्योजकासाठी.",
    "slide5_desc": "तुमच्या व्यवसायाभोवती तयार केलेले व्यवसाय सहाय्य, प्रोत्साहन आणि सरकारी योजना शोधा.",
    "slide6_prefix": "प्रत्येक",
    "slide6_main": "पिढीसाठी.",
    "slide6_desc": "दैनंदिन जीवन अधिक सुरक्षित करण्यासाठी डिझाइन केलेले सहाय्य, लाभ आणि योजना शोधा.",
    "builtForEveryCitizen": "प्रत्येक नागरिकासाठी निर्मित",
    "govSchemes": "सरकारी योजना",
    "citizenServices": "नागरिक सेवा",
    "digitalAccess": "डिजिटल प्रवेश",
    "businessSupport": "व्यवसाय सहाय्य",
    "independentCitizenPlatform": "स्वतंत्र नागरिक व्यासपीठ",
    "privacy": "गोपनीयता",
    "terms": "अटी",
    "platformDisclaimer": "योजना सेतू हे एक स्वतंत्र व्यासपीठ आहे जे नागरिकांना सरकारी योजना शोधण्यात मदत करते.",
    "allApplicationsSubtitle": "सर्व विभागांमधील येणाऱ्या योजना अर्जांचे पुनरावलोकन आणि व्यवस्थापन करा",
    "reviewLaterSubtitle": "पुढील मूल्यमापनासाठी रांगेत असलेले अर्ज. विभागीय पुनरावलोकनांना प्राधान्य द्या.",
    "schemeManagementSubtitle": "प्रकाशित सरकारी कल्याणकारी योजना आणि पात्रता पॅरामीटर्स तयार करा आणि व्यवस्थापित करा",
    "inReviewLaterQueue": "नंतर पुनरावलोकन रांगेत",
    "registeredJurisdiction": "नोंदणीकृत कार्यक्षेत्र",
    "directBenefit": "थेट लाभ",
    "schemeNotFound": "योजना सापडली नाही",
    "years": "वर्षे",
    "gender_male": "पुरुष",
    "gender_female": "स्त्री",
    "gender_other": "इतर",
    "category_Agriculture": "कृषी",
    "category_Finance": "वित्त",
    "category_Healthcare": "आरोग्य",
    "category_Housing": "गृहनिर्माण",
    "category_Education": "शिक्षण",
    "status_pending": "प्रलंबित",
    "status_in_review": "पुनरावलोकनात",
    "status_approved": "मंजूर",
    "status_rejected": "नाकारले",
    "notifTitle_notif-1": "पीएम-किसान अर्ज मंजूर झाला",
    "notifTitle_notif_1": "पीएम-किसान अर्ज मंजूर झाला",
    "notifMsg_notif-1": "तुमचा अर्ज (ID: PMK-2023-8942) यशस्वीरित्या पडताळला आणि मंजूर झाला आहे. हप्ता तुमच्या नोंदणीकृत बँक खात्यात जमा केला जाईल.",
    "notifMsg_notif_1": "तुमचा अर्ज (ID: PMK-2023-8942) यशस्वीरित्या पडताळला आणि मंजूर झाला आहे. हप्ता तुमच्या नोंदणीकृत बँक खात्यात जमा केला जाईल.",
    "notifTitle_notif-2": "नवीन पात्रता जुळणी: आयुष्मान भारत",
    "notifTitle_notif_2": "नवीन पात्रता जुळणी: आयुष्मान भारत",
    "notifMsg_notif-2": "तुमच्या अलीकडील प्रोफाइल अपडेटवर आधारित, तुम्ही आता आयुष्मान भारत पीएम-जेएवाय योजनेसाठी पात्र आहात.",
    "notifMsg_notif_2": "तुमच्या अलीकडील प्रोफाइल अपडेटवर आधारित, तुम्ही आता आयुष्मान भारत पीएम-जेएवाय योजनेसाठी पात्र आहात.",
    "notifTitle_notif-3": "कागदपत्र नाकारले: उत्पन्न प्रमाणपत्र अपडेट",
    "notifTitle_notif_3": "कागदपत्र नाकारले: उत्पन्न प्रमाणपत्र अपडेट",
    "notifMsg_notif-3": "आयुष्मान भारतसाठी प्रदान केलेले उत्पन्न प्रमाणपत्र ६ महिन्यांपेक्षा जुने आहे. कृपया पुढे जाण्यासाठी वैध दस्तऐवज पुन्हा अपलोड करा.",
    "notifMsg_notif_3": "आयुष्मान भारतसाठी प्रदान केलेले उत्पन्न प्रमाणपत्र ६ महिन्यांपेक्षा जुने आहे. कृपया पुढे जाण्यासाठी वैध दस्तऐवज पुन्हा अपलोड करा.",
    "notifTitle_notif-4": "प्रणाली देखभाल नियोजित",
    "notifTitle_notif_4": "प्रणाली देखभाल नियोजित",
    "notifMsg_notif-4": "या रविवारी पहाटे २:०० ते ६:०० या वेळेत पोर्टलची देखभाल होणार आहे.",
    "notifMsg_notif_4": "या रविवारी पहाटे २:०० ते ६:०० या वेळेत पोर्टलची देखभाल होणार आहे.",
    "badge_approved": "मंजूर",
    "badge_scheme_added": "नवीन योजना",
    "badge_action_required": "कृती आवश्यक",
    "badge_info": "घोषणा",
    "time_notif-1": "२ तासांपूर्वी",
    "time_notif-2": "५ तासांपूर्वी",
    "time_notif-3": "काल, दुपारी २:३०",
    "time_notif-4": "काल, सकाळी १०:१५",
    "rejection_income_expired": "प्रदान केलेले उत्पन्न प्रमाणपत्र ६ महिन्यांपेक्षा जुने आहे. कृपया वैध कागदपत्रांसह पुन्हा अर्ज करा.",
    "rejection_ayushman-pmjay": "प्रदान केलेले उत्पन्न प्रमाणपत्र ६ महिन्यांपेक्षा जुने आहे. कृपया वैध कागदपत्रांसह पुन्हा अर्ज करा.",
    "rejection_general": "प्रदान केलेले उत्पन्न प्रमाणपत्र ६ महिन्यांपेक्षा जुने आहे. कृपया वैध कागदपत्रांसह पुन्हा अर्ज करा.",
    "timeline_application_submitted": "अर्ज सादर केला",
    "timeline_document_verification": "कागदपत्र पडताळणी",
    "timeline_application_approved": "अर्ज मंजूर",
    "timeline_under_review": "पुनरावलोकनाधीन",
    "timeline_application_rejected": "अर्ज नाकारला",
    "timeline_decision": "निर्णय",
    "timelineDesc_application_submitted": "अर्ज प्राप्त झाला आणि पुनरावलोकन पथकाकडे सोपवला गेला.",
    "timelineDesc_document_verification": "सर्व सादर केलेली कागदपत्रे सक्षम अधिकाऱ्याकडून पडताळली गेली.",
    "timelineDesc_application_approved": "तुमचा अर्ज मंजूर झाला आहे. सबसिडी रक्कम लवकरच वितरित केली जाईल.",
    "timelineDesc_under_review": "प्राथमिक पडताळणी सुरू आहे.",
    "timelineDesc_application_rejected": "प्रदान केलेले उत्पन्न प्रमाणपत्र ६ महिन्यांपेक्षा जुने आहे. कृपया वैध कागदपत्रांसह पुन्हा अर्ज करा.",
    "scheme_pm-kisan": "पीएम-किसान सन्मान निधी",
    "scheme_pm-fby": "प्रधानमंत्री पीक विमा योजना (PMFBY)",
    "scheme_mudra-shishu": "मुद्रा शिशु कर्ज",
    "scheme_pmay-urban": "प्रधानमंत्री आवास योजना (PMAY - शहरी)",
    "scheme_ayushman-pmjay": "आयुष्मान भारत पीएम-जेएवाय",
    "scheme_standup-india": "स्टँड-अप इंडिया योजना",
    "scheme_national-scholarship": "राष्ट्रीय शिष्यवृत्ती पोर्टल (NSP मॅट्रिकोत्तर)",
    "scheme_udyam-msme-subsidy": "उद्यम एमएसएमई तंत्रज्ञान आणि क्रेडिट सबसिडी",
    "scheme_pm-svanidhi": "पीएम स्वनिधी योजना",
    "scheme_pm-vishwakarma": "पीएम विश्वकर्मा कौशल्य सन्मान",
    "dept_pm-kisan": "कृषी आणि शेतकरी कल्याण मंत्रालय",
    "dept_pm-fby": "कृषी आणि शेतकरी कल्याण मंत्रालय",
    "dept_mudra-shishu": "वित्त मंत्रालय",
    "dept_pmay-urban": "गृहनिर्माण आणि शहरी व्यवहार मंत्रालय",
    "dept_ayushman-pmjay": "राष्ट्रीय आरोग्य प्राधिकरण",
    "dept_standup-india": "वित्त मंत्रालय",
    "dept_national-scholarship": "सामाजिक न्याय आणि सक्षमीकरण मंत्रालय",
    "dept_udyam-msme-subsidy": "सूक्ष्म, लघु आणि मध्यम उद्योग मंत्रालय",
    "dept_pm-svanidhi": "गृहनिर्माण आणि शहरी व्यवहार मंत्रालय",
    "dept_pm-vishwakarma": "एमएसएमई मंत्रालय",
    "benefit_pm-kisan": "₹६,००० / वर्ष",
    "benefit_pm-fby": "पीक विमा",
    "benefit_mudra-shishu": "₹५०,००० पर्यंत",
    "benefit_pmay-urban": "₹२.६७ लाखांपर्यंत सबसिडी",
    "benefit_ayushman-pmjay": "₹५ लाख / कुटुंब / वर्ष",
    "benefit_standup-india": "₹१० लाख ते ₹१ कोटी",
    "benefit_national-scholarship": "₹५०,००० / वर्ष पर्यंत",
    "benefit_udyam-msme-subsidy": "१५% भांडवली सबसिडी",
    "benefit_pm-svanidhi": "₹५०,००० पर्यंत",
    "benefit_pm-vishwakarma": "₹१५,००० टूलकिट + कर्ज",
    "benefitDetail_pm-kisan": "थेट लाभ हस्तांतरण (DBT)",
    "benefitDetail_pm-fby": "₹२ लाखांपर्यंत कव्हर",
    "benefitDetail_mudra-shishu": "विनातारण कर्ज",
    "benefitDetail_pmay-urban": "व्याज सबसिडी योजना",
    "benefitDetail_ayushman-pmjay": "कॅशलेस आरोग्य कव्हर",
    "benefitDetail_standup-india": "ग्रीनफील्ड उद्योग कर्ज",
    "benefitDetail_national-scholarship": "शिक्षण शुल्क + विद्यावेतन",
    "benefitDetail_udyam-msme-subsidy": "तंत्रज्ञान सुधारणेसाठी ₹१५ लाखांपर्यंत",
    "benefitDetail_pm-svanidhi": "७% व्याज सबसिडी",
    "benefitDetail_pm-vishwakarma": "५% व्याजाने ₹३ लाखांपर्यंत",
    "deadline_pm-kisan": "१५ दिवसांत बंद",
    "deadline_pm-fby": "३० सप्टेंबर २०२६ रोजी बंद",
    "deadline_mudra-shishu": "नेहमी सुरू",
    "deadline_pmay-urban": "३१ डिसेंबर २०२६ रोजी बंद",
    "deadline_ayushman-pmjay": "नेहमी सुरू",
    "deadline_standup-india": "३० नोव्हेंबर २०२६ रोजी बंद",
    "deadline_national-scholarship": "१५ ऑक्टोबर २०२६ रोजी बंद",
    "deadline_udyam-msme-subsidy": "३१ ऑक्टोबर २०२६ रोजी बंद",
    "deadline_pm-svanidhi": "नेहमी सुरू",
    "deadline_pm-vishwakarma": "१५ नोव्हेंबर २०२६ रोजी बंद",
    "desc_pm-kisan": "शेतकऱ्यांच्या आर्थिक गरजा पूर्ण करण्यासाठी देशातील सर्व शेतकरी कुटुंबांना उत्पन्न सहाय्य देणारी योजना.",
    "desc_pm-fby": "नैसर्गिक आपत्तीमुळे पिकांचे नुकसान झालेल्या शेतकऱ्यांना आर्थिक सहाय्य देणारी पीक विमा योजना.",
    "desc_mudra-shishu": "सूक्ष्म उद्योग आणि लहान व्यवसायांसाठी ₹५०,००० पर्यंतचे विनातारण संस्थात्मक कर्ज.",
    "desc_pmay-urban": "आर्थिकदृष्ट्या दुर्बल घटकांसाठी परवडणाऱ्या घरांच्या खरेदी किंवा बांधकामासाठी क्रेडिट लिंक्ड सबसिडी योजना.",
    "desc_ayushman-pmjay": "मोफत द्वितीयक आणि तृतीयक रुग्णालयात दाखल होण्यासाठी जगातील सर्वात मोठी सरकारी आरोग्य विमा योजना.",
    "desc_standup-india": "ग्रीनफील्ड उपक्रमांसाठी अनुसूचित जाती/जमाती आणि महिला उद्योजकांना ₹१० लाख ते ₹१ कोटींचे बँक कर्ज.",
    "desc_national-scholarship": "उच्च शिक्षण घेणाऱ्या गुणवंत विद्यार्थ्यांना आर्थिक सहाय्य.",
    "desc_udyam-msme-subsidy": "नोंदणीकृत एमएसएमईसाठी भांडवली गुंतवणूक आणि तंत्रज्ञान सुधारणा सबसिडी.",
    "desc_pm-svanidhi": "फेरीवाल्यांसाठी ₹५०,००० पर्यंतचे खेळते भांडवल कर्ज मिळवून देणारी विशेष योजना.",
    "desc_pm-vishwakarma": "पारंपरिक कारागीर आणि शिल्पकारांसाठी कौशल्य प्रशिक्षण, टूलकिट आणि विनातारण कर्ज सहाय्य.",
    "overview_pm-kisan": "पीएम-किसान योजनेअंतर्गत, देशभरातील सर्व शेतकरी कुटुंबांना दर चार महिन्यांनी ₹२,००० च्या तीन समान हप्त्यांमध्ये वर्षाला ₹६,००० चे उत्पन्न सहाय्य दिले जाते.",
    "overview_pm-fby": "पीएमएफबीवाय सर्व अन्न आणि तेलबिया पिकांसाठी पेरणीपूर्व ते काढणीनंतरच्या नैसर्गिक जोखमींविरुद्ध विमा संरक्षण प्रदान करते.",
    "overview_mudra-shishu": "प्रधानमंत्री मुद्रा योजनेअंतर्गत, लहान उत्पादन युनिट्स, सेवा युनिट्स, दुकानदार आणि कारागिरांसाठी ₹५०,००० पर्यंतची कर्जे मिळतात.",
    "overview_pmay-urban": "पात्र शहरी कुटुंबांना घरांची खरेदी, बांधकाम किंवा विस्तारासाठी गृहकर्जावर व्याज सबसिडी प्रदान करते.",
    "overview_ayushman-pmjay": "सार्वजनिक आणि पॅनेलवरील खाजगी रुग्णालयांमध्ये दरवर्षी प्रति कुटुंब ₹५ लाखांचे आरोग्य संरक्षण प्रदान करते.",
    "overview_standup-india": "उत्पादन, सेवा, कृषी-संलग्न किंवा व्यापार क्षेत्रात नवीन उपक्रम उभारण्यासाठी बँक कर्जाची सुविधा देते.",
    "overview_national-scholarship": "पात्र विद्यार्थ्यांच्या पडताळणी केलेल्या बँक खात्यात थेट निर्वाह भत्ता, अभ्यासक्रम शुल्क परतावा प्रदान करते.",
    "overview_udyam-msme-subsidy": "विशिष्ट उप-क्षेत्रांमध्ये प्रगत तंत्रज्ञानाचा अवलंब करण्यासाठी १५% पर्यंत आगाऊ भांडवली सबसिडी देते.",
    "overview_pm-svanidhi": "फेरीवाल्यांना व्याज सबसिडी आणि डिजिटल व्यवहारांच्या प्रोत्साहनासह खेळते भांडवल कर्ज उपलब्ध करून देते.",
    "overview_pm-vishwakarma": "पीएम विश्वकर्मा प्रमाणपत्र आणि आयडी, ₹५००/दिवस स्टायपेंडसह कौशल्य प्रशिक्षण, ₹१५,००० टूलकिट अनुदान आणि ५% व्याजाने कर्ज प्रदान करते."
}

OR_OVERRIDES = {
    "adminLogin": "ପ୍ରଶାସକ ଲଗଇନ୍",
    "loginAsAdmin": "ପ୍ରଶାସକ ଭାବରେ ଲଗଇନ୍ କରନ୍ତୁ",
    "backToUserLogin": "ଉପଭୋକ୍ତା ଲଗଇନକୁ ଫେରନ୍ତୁ",
    "emailOrMobile": "ଇମେଲ୍ କିମ୍ବା ମୋବାଇଲ୍ ନମ୍ବର",
    "password": "ପାସୱାର୍ଡ",
    "adminId": "ପ୍ରଶାସକ ଆଇଡି",
    "fullName": "ପୂରା ନାମ",
    "email": "ଇମେଲ୍",
    "mobile": "ମୋବାଇଲ୍",
    "confirmPassword": "ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ",
    "createAccount": "ଖାତା ତିଆରି କରନ୍ତୁ",
    "newUserRegister": "ନୂତନ ଉପଭୋକ୍ତା? ଏଠାରେ ପଞ୍ଜୀକରଣ କରନ୍ତୁ",
    "alreadyHaveAccount": "ପୂର୍ବରୁ ଖାତା ଅଛି? ଏଠାରେ ଲଗଇନ୍ କରନ୍ତୁ",
    "forgotPassword": "ପାସୱାର୍ଡ ଭୁଲିଗଲେ କି?",
    "termsAgree": "ମୁଁ ସେବା ସର୍ତ୍ତାବଳୀ ଏବଂ ଗୋପନୀୟତା ନୀତି ସହିତ ସହମତ",
    "schemesSelected": "{count} ଟି ଯୋଜନା ଚୟନ କରାଯାଇଛି",
    "applyToSelected": "ଚୟନିତ ଯୋଜନାରେ ଆବେଦନ କରନ୍ତୁ",
    "profileCompletionBannerTitle": "ଆପଣଙ୍କର ପ୍ରୋଫାଇଲ୍ ସଂପୂର୍ଣ୍ଣ କରନ୍ତୁ",
    "profileCompletionBannerDesc": "ଗୋଟିଏ କ୍ଲିକରେ ଆବେଦନ ସ୍ୱୟଂଚାଳିତ ଭାବରେ ପୂରଣ କରନ୍ତୁ। ବର୍ତ୍ତମାନ {percent}% ସଂପୂର୍ଣ୍ଣ ହୋଇଛି।",
    "backToResults": "ଫଳାଫଳକୁ ଫେରନ୍ତୁ",
    "schemeOverview": "ଯୋଜନା ସମୀକ୍ଷା",
    "eligibilityCriteria": "ଯୋଗ୍ୟତା ମାନଦଣ୍ଡ",
    "requiredDocuments": "ଆବଶ୍ୟକୀୟ ଦସ୍ତାବିଜ",
    "urgentDeadline": "ଜରୁରୀ ଶେଷ ତାରିଖ",
    "applicationStats": "ଆବେଦନ ପରିସଂଖ୍ୟାନ",
    "processingTime": "ପ୍ରକ୍ରିୟାକରଣ ସମୟ",
    "approvalRate": "ଅନୁମୋଦନ ହାର",
    "application": "ଆବେଦନ",
    "applyingTo": "ଆବେଦନ କରୁଛନ୍ତି:",
    "applyingAs": "ଆବେଦନକାରୀ ସ୍ୱରୂପ",
    "applicantDetails": "ଆବେଦନକାରୀଙ୍କ ବିବରଣୀ",
    "bankDetails": "ବ୍ୟାଙ୍କ ବିବରଣୀ",
    "schemeRequirements": "ଯୋଜନା ଆବଶ୍ୟକତା",
    "autoFilled": "ସ୍ୱୟଂଚାଳିତ ପୂରଣ",
    "cancel": "ବାତିଲ୍ କରନ୍ତୁ",
    "submitApplication": "ଆବେଦନ ଦାଖଲ କରନ୍ତୁ",
    "applicationSubmittedSuccess": "ଆବେଦନ ସଫଳତାର ସହିତ ଦାଖଲ ହୋଇଛି!",
    "myBusinessesTitle": "ମୋର ବ୍ୟବସାୟ",
    "myBusinessesDesc": "ଆପଣଙ୍କର ଏଣ୍ଟରପ୍ରାଇଜ୍ ପ୍ରୋଫାଇଲ୍ ପରିଚାଳନା କରନ୍ତୁ ଏବଂ ସରକାରୀ ଯୋଜନା ଖୋଜନ୍ତୁ।",
    "addNewBusiness": "ନୂତନ ବ୍ୟବସାୟ ଯୋଡନ୍ତୁ",
    "editBusiness": "ବ୍ୟବସାୟ ସମ୍ପାଦନ କରନ୍ତୁ",
    "checkEligibility": "ଯୋଗ୍ୟତା ଯାଞ୍ଚ କରନ୍ତୁ",
    "delete": "ଡିଲିଟ୍ କରନ୍ତୁ",
    "edit": "ସମ୍ପାଦନ କରନ୍ତୁ",
    "businessName": "ଆଇନଗତ ବ୍ୟବସାୟ ନାମ",
    "businessType": "ବ୍ୟବସାୟ ପ୍ରକାର",
    "industrySector": "ଶିଳ୍ପ କ୍ଷେତ୍ର",
    "gstNumber": "ଜିଏସଟି ନମ୍ବର",
    "panNumber": "ପାନ୍ ନମ୍ବର",
    "annualTurnover": "ବାର୍ଷିକ କାରବାର",
    "employeeCount": "କର୍ମଚାରୀ ସଂଖ୍ୟା",
    "yearsInOperation": "କାର୍ଯ୍ୟରତ ବର୍ଷ",
    "udyamNumber": "ଉଦ୍ୟମ ପଞ୍ଜୀକରଣ ନମ୍ବର",
    "saveBusiness": "ବ୍ୟବସାୟ ପ୍ରୋଫାଇଲ୍ ସଂରକ୍ଷଣ କରନ୍ତୁ",
    "pending": "ବିଚାରାଧୀନ",
    "approved": "ଅନୁମୋଦିତ",
    "rejected": "ପ୍ରତ୍ୟାଖ୍ୟାନ",
    "inReview": "ସମୀକ୍ଷାଧୀନ",
    "markAllRead": "ସବୁ ପଢ଼ା ହୋଇଛି ବୋଲି ଚିହ୍ନଟ କରନ୍ତୁ",
    "today": "ଆଜି",
    "yesterday": "ଗତକାଲି",
    "shareEligibilityTitle": "ଆପଣଙ୍କ ଯୋଗ୍ୟତା ସେୟାର କରନ୍ତୁ",
    "shareEligibilitySubtitle": "ଆପଣ ଯୋଗ୍ୟ ଥିବା ସରକାରୀ ଯୋଜନାର ସାରାଂଶ ପଠାନ୍ତୁ।",
    "copyLink": "ଲିଙ୍କ୍ କପି କରନ୍ତୁ",
    "downloadPdf": "ପିଡିଏଫ୍ ଡାଉନଲୋଡ୍ କରନ୍ତୁ",
    "linkCopiedToast": "ଲିଙ୍କ୍ କ୍ଲିପବୋର୍ଡକୁ କପି ହୋଇଛି!",
    "platformOverview": "ପ୍ଲାଟଫର୍ମ ସମୀକ୍ଷା",
    "totalUsers": "ମୋଟ ଉପଭୋକ୍ତା",
    "totalBusinesses": "ମୋଟ ବ୍ୟବସାୟ",
    "totalApplications": "ମୋଟ ଆବେଦନ",
    "pendingApplications": "ବିଚାରାଧୀନ ଆବେଦନ",
    "approvedApplications": "ଅନୁମୋଦିତ ଆବେଦନ",
    "rejectedApplications": "ପ୍ରତ୍ୟାଖ୍ୟାନ ଆବେଦନ",
    "applicationsTrend": "ଆବେଦନ ଟ୍ରେଣ୍ଡ",
    "applicationsByCategory": "ବର୍ଗ ଅନୁଯାୟୀ ଆବେଦନ",
    "topAppliedSchemes": "ସର୍ବାଧିକ ଆବେଦନ ହୋଇଥିବା ଯୋଜନା",
    "reviewVerdict": "ସମୀକ୍ଷା ରାୟ",
    "rejectionReasonPrompt": "ପ୍ରତ୍ୟାଖ୍ୟାନ କାରଣ (ବାଧ୍ୟତାମୂଳକ)",
    "approveApplication": "ଆବେଦନ ଅନୁମୋଦନ କରନ୍ତୁ",
    "rejectApplication": "ଆବେଦନ ପ୍ରତ୍ୟାଖ୍ୟାନ କରନ୍ତୁ",
    "markReviewLater": "ପରେ ସମୀକ୍ଷା କରନ୍ତୁ",
    "savedItems": "ସଂରକ୍ଷିତ ଆଇଟମ୍",
    "reviewNow": "ବର୍ତ୍ତମାନ ସମୀକ୍ଷା କରନ୍ତୁ",
    "addNewScheme": "ନୂତନ ଯୋଜନା ଯୋଡନ୍ତୁ",
    "editScheme": "ଯୋଜନା ସମ୍ପାଦନ କରନ୍ତୁ",
    "saveScheme": "ଯୋଜନା ସଂରକ୍ଷଣ କରନ୍ତୁ",
    "deleteSchemeConfirm": "ଆପଣ ନିଶ୍ଚିତ କି ଏହି ଯୋଜନାଟି ହଟାଇବାକୁ ଚାହାଁନ୍ତି?",
    "searchLanguage": "ଭାଷା ଖୋଜନ୍ତୁ...",
    "switchProfileContext": "ପ୍ରୋଫାଇଲ୍ ପ୍ରସଙ୍ଗ ପରିବର୍ତ୍ତନ କରନ୍ତୁ",
    "youContext": "{name} (ବ୍ୟକ୍ତିଗତ)",
    "personalContextTitle": "ବ୍ୟକ୍ତିଗତ ପ୍ରୋଫାଇଲ୍",
    "personalDashboardDesc": "ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ଅନୁଯାୟୀ ବ୍ୟକ୍ତିଗତ ନାଗରିକ ସବସିଡି ଏବଂ କଲ୍ୟାଣକାରୀ ଯୋଜନା।",
    "businessDashboardDesc": "ଆପଣଙ୍କ ବ୍ୟବସାୟ ପାଇଁ ଏଣ୍ଟରପ୍ରାଇଜ୍ ସବସିଡି ଏବଂ ଅନୁଦାନ।",
    "eligibleSchemesDiscovered": "ଯୋଗ୍ୟ ଯୋଜନା ଖୋଜି ପାଇଲେ",
    "noMatchingSchemesFound": "କୌଣସି ଯୋଜନା ମିଳିଲା ନାହିଁ",
    "noSchemesFoundDesc": "ଆପଣଙ୍କ ଖୋଜିବା ଶବ୍ଦ ବଦଳାନ୍ତୁ କିମ୍ବା ଫିଲ୍ଟର ରିସେଟ୍ କରନ୍ତୁ।",
    "resetFilters": "ଫିଲ୍ଟର ରିସେଟ୍ କରନ୍ତୁ",
    "clear": "ସଫା କରନ୍ତୁ",
    "urgentDeadlineDesc": "ଏହି ଯୋଜନା ପାଇଁ ଆବେଦନ ଶୀଘ୍ର ବନ୍ଦ ହେବ ({deadline})। ତୁରନ୍ତ ଦାଖଲ କରନ୍ତୁ।",
    "businessApplication": "ବ୍ୟବସାୟିକ ଆବେଦନ",
    "personalApplication": "ବ୍ୟକ୍ତିଗତ ଆବେଦନ",
    "businessContext": "ବ୍ୟବସାୟ ପ୍ରସଙ୍ଗ",
    "selectRegisteredEnterprise": "ପଞ୍ଜୀକୃତ ଏଣ୍ଟରପ୍ରାଇଜ୍ ଚୟନ କରନ୍ତୁ",
    "applyingAsIndividual": "ବ୍ୟକ୍ତିଗତ ନାଗରିକ ଭାବରେ ଆବେଦନ କରୁଛନ୍ତି",
    "personal": "ବ୍ୟକ୍ତିଗତ",
    "business": "ବ୍ୟବସାୟ",
    "ageGender": "ବୟସ ଏବଂ ଲିଙ୍ଗ",
    "stateCategory": "ରାଜ୍ୟ ଏବଂ ବର୍ଗ",
    "annualIncome": "ବାର୍ଷିକ ଆୟ",
    "businessDetails": "ବ୍ୟବସାୟ ବିବରଣୀ",
    "legalName": "ଆଇନଗତ ନାମ",
    "turnoverSector": "କାରବାର ଏବଂ କ୍ଷେତ୍ର",
    "bankName": "ବ୍ୟାଙ୍କ ନାମ",
    "accountNumber": "ଖାତା ନମ୍ବର",
    "ifscCode": "ଆଇଏଫଏସସି କୋଡ୍",
    "cultivableLandHolding": "ମୋଟ ଚାଷଜମି (ହେକ୍ଟରରେ)",
    "requiredCreditAmount": "ଆବଶ୍ୟକ ଋଣ ରାଶି (₹)",
    "uploadDocumentProof": "ଆବଶ୍ୟକ ଦସ୍ତାବିଜ ଅପଲୋଡ୍ କରନ୍ତୁ (PDF / ଫଟୋ)",
    "clickToReplaceDocs": "ଅତିରିକ୍ତ ଫାଇଲ୍ ଯୋଡ଼ିବା ପାଇଁ କ୍ଲିକ୍ କରନ୍ତୁ",
    "appReceivedRefId": "ଆପଣଙ୍କ ଆବେଦନ ଏହି ରେଫରେନ୍ସ ଆଇଡି ସହିତ ଗ୍ରହଣ କରାଯାଇଛି:",
    "trackInMyApplications": "ମୋର ଆବେଦନରେ ଟ୍ରାକ୍ କରନ୍ତୁ",
    "returnToDashboard": "ଡ୍ୟାସବୋର୍ଡକୁ ଫେରନ୍ତୁ",
    "myAppsSubtitle": "ଆପଣଙ୍କର ସମସ୍ତ ସରକାରୀ ଯୋଜନା ଆବେଦନ ରିଅଲ୍-ଟାଇମରେ ମନିଟରିଂ କରନ୍ତୁ",
    "searchApplications": "ଆବେଦନ ଖୋଜନ୍ତୁ...",
    "allApplicationsTab": "ସମସ୍ତ ଆବେଦନ ({count})",
    "personalTab": "ବ୍ୟକ୍ତିଗତ ({count})",
    "businessTab": "ବ୍ୟବସାୟ ({count})",
    "noApplicationsFound": "କୌଣସି ଆବେଦନ ମିଳିଲା ନାହିଁ",
    "noAppsMatchQuery": "ଆପଣଙ୍କ ଅନୁସନ୍ଧାନ ସହିତ କୌଣସି ଆବେଦନ ମେଳ ଖାଉନାହିଁ।",
    "noAppsInCat": "ଆପଣ ଏହି ବର୍ଗରେ କୌଣସି ଆବେଦନ କରିନାହାଁନ୍ତି।",
    "appRegisteredUnder": "{category} ପଦକ୍ଷେପ ଅଧୀନରେ ପଞ୍ଜୀକୃତ ଆବେଦନ।",
    "appTimelineVerification": "ଆବେଦନ ଟାଇମଲାଇନ୍ ଏବଂ ଯାଞ୍ଚ",
    "state": "ରାଜ୍ୟ",
    "close": "ବନ୍ଦ କରନ୍ତୁ",
    "notAdded": "ଯୋଡା ହୋଇନାହିଁ",
    "udyamRegNumber": "ଉଦ୍ୟମ ପଞ୍ଜୀକରଣ ନଂ",
    "addAnotherBusiness": "ଅନ୍ୟ ଏକ ବ୍ୟବସାୟ ଯୋଡନ୍ତୁ",
    "addAnotherBusinessDesc": "ଶିଳ୍ପ-ନିର୍ଦ୍ଦିଷ୍ଟ ସବସିଡି ଆବିଷ୍କାର କରିବାକୁ ଅତିରିକ୍ତ ଏଣ୍ଟରପ୍ରାଇଜ୍ ପଞ୍ଜିକରଣ କରନ୍ତୁ।",
    "confirmDelete": "ଡିଲିଟ୍ ନିଶ୍ଚିତ କରନ୍ତୁ",
    "deleteBusinessConfirm": "ଆପଣ ନିଶ୍ଚିତ କି ଏହି ବ୍ୟବସାୟ ପ୍ରୋଫାଇଲ୍ ଡିଲିଟ୍ କରିବାକୁ ଚାହାଁନ୍ତି?",
    "enterAccurateDetailsBiz": "ଯୋଗ୍ୟ ବ୍ୟବସାୟ ସବସିଡି ପାଇବାକୁ ସଠିକ୍ ବିବରଣୀ ପ୍ରବେଶ କରନ୍ତୁ।",
    "basicInformation": "୧. ମୌଳିକ ସୂଚନା",
    "registrationsIdentifiers": "୨. ପଞ୍ଜୀକରଣ ଏବଂ ପରିଚୟପତ୍ର",
    "operationalContactDetails": "୩. କାର୍ଯ୍ୟକ୍ଷମ ଏବଂ ଯୋଗାଯୋଗ ବିବରଣୀ",
    "businessAddress": "ବ୍ୟବସାୟ ଠିକଣା",
    "contactPhone": "ଯୋଗାଯୋଗ ଫୋନ୍",
    "contactEmail": "ଯୋଗାଯୋଗ ଇମେଲ୍",
    "bookmarksSubtitle": "ଶୀଘ୍ର ପ୍ରବେଶ ପାଇଁ ଆପଣଙ୍କର ସଂରକ୍ଷିତ ସରକାରୀ ଯୋଜନା",
    "noBookmarksYet": "କୌଣସି ବୁକମାର୍କ ନାହିଁ",
    "noBookmarksDesc": "ଆପଣ କୌଣସି ଯୋଜନା ସଂରକ୍ଷଣ କରିନାହାଁନ୍ତି। ଡ୍ୟାସବୋର୍ଡରୁ ଷ୍ଟାର୍ ଆଇକନ୍ କ୍ଲିକ୍ କରି ସଂରକ୍ଷଣ କରନ୍ତୁ।",
    "browseSchemes": "ଯୋଜନା ବ୍ରାଉଜ୍ କରନ୍ତୁ",
    "update": "ଅପଡେଟ୍",
    "unread": "ଅପଠିତ",
    "updateDocument": "ଦସ୍ତାବିଜ ଅପଡେଟ୍ କରନ୍ତୁ",
    "notificationsSubtitle": "ଆବେଦନ ସମୀକ୍ଷା ଏବଂ ନୂତନ ଯୋଜନା ବିଷୟରେ ଅପଡେଟ୍ ରୁହନ୍ତୁ",
    "noNotifications": "କୌଣସି ବିଜ୍ଞପ୍ତି ନାହିଁ",
    "allCaughtUp": "ଆପଣ ସମସ୍ତ ବିଜ୍ଞପ୍ତି ଦେଖିସାରିଛନ୍ତି!",
    "citizenId": "ନାଗରିକ ଆଇଡି",
    "profileCompletedPercent": "{percent}% ପ୍ରୋଫାଇଲ୍ ସଂପୂର୍ଣ୍ଣ",
    "cancelEdit": "ସମ୍ପାଦନ ବାତିଲ୍ କରନ୍ତୁ",
    "editProfile": "ପ୍ରୋଫାଇଲ୍ ସମ୍ପାଦନ କରନ୍ତୁ",
    "age": "ବୟସ",
    "saveChanges": "ପରିବର୍ତ୍ତନ ସଂରକ୍ଷଣ କରନ୍ତୁ",
    "linkedVerified": "ସଂଯୁକ୍ତ ଏବଂ ଯାଞ୍ଚ ହୋଇଛି",
    "verificationDocuments": "ଯାଞ୍ଚ ଦସ୍ତାବିଜ",
    "notUploadedRequired": "ଅପଲୋଡ୍ ହୋଇନାହିଁ (ଆବଶ୍ୟକ)",
    "uploaded": "ଅପଲୋଡ୍ ହୋଇଛି",
    "uploadProof": "ପ୍ରମାଣପତ୍ର ଅପଲୋଡ୍ କରନ୍ତୁ",
    "updateBankDetails": "ବ୍ୟାଙ୍କ ବିବରଣୀ ଅପଡେଟ୍ କରନ୍ତୁ",
    "saveBankDetails": "ବ୍ୟାଙ୍କ ବିବରଣୀ ସଂରକ୍ଷଣ କରନ୍ତୁ",
    "applicantProfile": "ଆବେଦନକାରୀ ପ୍ରୋଫାଇଲ୍",
    "enterpriseProfile": "ଏଣ୍ଟରପ୍ରାଇଜ୍ ପ୍ରୋଫାଇଲ୍",
    "verifiedResident": "ଯାଞ୍ଚ ହୋଇଥିବା ବାସିନ୍ଦା",
    "eligibleSchemesTitle": "ଯୋଗ୍ୟ ଯୋଜନା ({count})",
    "adminOverviewSubtitle": "ଯୋଜନା ପଞ୍ଜୀକରଣ ଏବଂ ବିଭାଗୀୟ ନିଷ୍ପତ୍ତି ପାଇଁ ଡ୍ୟାସବୋର୍ଡ",
    "monthlyIntakeSubtitle": "ମାସିକ ଆବେଦନ ବଣ୍ଟନ",
    "sectorShareBreakdown": "କ୍ଷେତ୍ର ଅଂଶ ବିଶ୍ଳେଷଣ",
    "total": "ମୋଟ",
    "estVolume": "ଆନୁମାନିକ ପରିମାଣ",
    "applicantsCount": "{count} ଆବେଦନକାରୀ",
    "searchAdminPlaceholder": "ଆପ୍ ଆଇଡି, ବ୍ୟବହାରକାରୀ କିମ୍ବା ଯୋଜନା ଦ୍ୱାରା ଖୋଜନ୍ତୁ...",
    "status": "ସ୍ଥିତି",
    "allStatuses": "ସମସ୍ତ ସ୍ଥିତି",
    "fromDate": "ଏହି ତାରିଖରୁ",
    "toDate": "ଏହି ତାରିଖ ପର୍ଯ୍ୟନ୍ତ",
    "reset": "ରିସେଟ୍",
    "appId": "ଆପ୍ ଆଇଡି",
    "applicant": "ଆବେଦନକାରୀ",
    "scheme": "ଯୋଜନା",
    "entity": "ସଂସ୍ଥା",
    "action": "କାର୍ଯ୍ୟାନୁଷ୍ଠାନ",
    "noAppsMatchFilters": "କୌଣସି ଆବେଦନ ଫିଲ୍ଟର ସହିତ ମେଳ ଖାଉନାହିଁ।",
    "individual": "ବ୍ୟକ୍ତିଗତ",
    "reviewApplication": "ଆବେଦନ ସମୀକ୍ଷା",
    "targetGovInitiative": "ଲକ୍ଷ୍ୟଧାର୍ଯ୍ୟ ସରକାରୀ ପଦକ୍ଷେପ",
    "finalizeVerdictSubtitle": "ଯାଞ୍ଚ ରାୟ ଚୂଡ଼ାନ୍ତ କରନ୍ତୁ କିମ୍ବା ପରବର୍ତ୍ତୀ ସମୀକ୍ଷା ପାଇଁ ରଖନ୍ତୁ।",
    "rejectionNotesPlaceholder": "ପ୍ରତ୍ୟାଖ୍ୟାନ କଲେ ବାଧ୍ୟତାମୂଳକ କାରଣ ଲେଖନ୍ତୁ...",
    "noAppsInReviewLater": "ପରବର୍ତ୍ତୀ ସମୀକ୍ଷା ଧାଡ଼ିରେ କୌଣସି ଆବେଦନ ନାହିଁ",
    "noAppsInReviewLaterDesc": "ଆବେଦନଗୁଡ଼ିକ ସମୀକ୍ଷା କରିବା ସମୟରେ, ଆପଣ ପରବର୍ତ୍ତୀ ସମୀକ୍ଷା ପାଇଁ ଏଠାରେ ରଖିପାରିବେ।",
    "remove": "ହଟାନ୍ତୁ",
    "queuedOn": "ଧାଡ଼ିରେ ଯୋଡ଼ାଗଲା",
    "auditStage": "ଅଡିଟ୍ ପର୍ଯ୍ୟାୟ",
    "searchSchemesPlaceholder": "ଶୀର୍ଷକ କିମ୍ବା ମନ୍ତ୍ରଣାଳୟ ଦ୍ୱାରା ଯୋଜନା ଖୋଜନ୍ତୁ...",
    "active": "ସକ୍ରିୟ",
    "enterpriseScheme": "ଏଣ୍ଟରପ୍ରାଇଜ୍ ଯୋଜନା",
    "citizenScheme": "ନାଗରିକ ଯୋଜନା",
    "alwaysOpen": "ସର୍ବଦା ଖୋଲା",
    "confirmDeleteScheme": "ଯୋଜନା ଡିଲିଟ୍ ନିଶ୍ଚିତ କରନ୍ତୁ",
    "deleteSchemeConfirmDesc": "ଆପଣ ନିଶ୍ଚିତ କି ଏହି ଯୋଜନାଟି ଡାଇରେକ୍ଟୋରୀରୁ ହଟାଇବାକୁ ଚାହାଁନ୍ତି?",
    "configureEligibilitySubtitle": "ଯୋଗ୍ୟତା ମାନଦଣ୍ଡ ଏବଂ ପ୍ରକାଶନ ପାରାମିଟର ବିନ୍ୟାସ କରନ୍ତୁ",
    "schemeNameLabel": "ଯୋଜନାର ନାମ",
    "ministryDepartment": "ମନ୍ତ୍ରଣାଳୟ / ବିଭାଗ",
    "description": "ବର୍ଣ୍ଣନା",
    "descriptionPlaceholder": "ଯୋଜନା ସୁବିଧା ଏବଂ ଯୋଗ୍ୟତାର ବିସ୍ତୃତ ବର୍ଣ୍ଣନା...",
    "benefitHeadline": "ସୁବିଧା ଶୀର୍ଷକ (ଯଥା: ₹୬,୦୦୦ / ବର୍ଷ)",
    "benefitDetail": "ସୁବିଧା ବିବରଣୀ (ଯଥା: ପ୍ରତ୍ୟକ୍ଷ ଲାଭ ହସ୍ତାନ୍ତର)",
    "eligibilityOperations": "୨. ଯୋଗ୍ୟତା ଏବଂ କାର୍ଯ୍ୟ",
    "ageRange": "ବୟସ ସୀମା (ସର୍ବନିମ୍ନ - ସର୍ବାଧିକ)",
    "maxAnnualIncome": "ସର୍ବାଧିକ ବାର୍ଷିକ ଆୟ",
    "applicationDeadline": "ଆବେଦନର ଶେଷ ତାରିଖ",
    "isBusinessSchemeToggleLabel": "ଏହା ଏକ ବ୍ୟବସାୟ / ଏଣ୍ଟରପ୍ରାଇଜ୍ ଯୋଜନା (MSME ଏବଂ ବ୍ୟବସାୟ ପାଇଁ ଉପଲବ୍ଧ)",
    "adminLoginSubtitle": "କେନ୍ଦ୍ରୀୟ ପ୍ରଶାସନ ପୋର୍ଟାଲ୍ ପ୍ରବେଶ କରନ୍ତୁ",
    "authenticating": "ପ୍ରମାଣୀକରଣ ଚାଲିଛି...",
    "asPerOfficialDocs": "ସରକାରୀ ଦସ୍ତାବିଜ ଅନୁଯାୟୀ",
    "mobilePlaceholder": "୧୦-ଅଙ୍କ ବିଶିଷ୍ଟ ମୋବାଇଲ୍",
    "min8Chars": "ସର୍ବନିମ୍ନ ୮ ଅକ୍ଷର",
    "slide1_prefix": "ପ୍ରତ୍ୟେକ",
    "slide1_main": "ନାଗରିକଙ୍କ ପାଇଁ।",
    "slide1_desc": "ଆପଣଙ୍କ ପାଇଁ ଉପଯୁକ୍ତ ସରକାରୀ ଯୋଜନା ଏବଂ ସୁବିଧା ଗୋଟିଏ ସ୍ଥାନରେ ଖୋଜନ୍ତୁ।",
    "slide2_prefix": "ପ୍ରତ୍ୟେକ",
    "slide2_main": "ଛାତ୍ରଙ୍କ ପାଇଁ।",
    "slide2_desc": "ଆପଣଙ୍କୁ ଆଗକୁ ବଢ଼ିବାରେ ସାହାଯ୍ୟ କରିବା ପାଇଁ ଛାତ୍ରବୃତ୍ତି ଏବଂ ଶିକ୍ଷା ସହାୟତା ଖୋଜନ୍ତୁ।",
    "slide3_prefix": "ପ୍ରତ୍ୟେକ",
    "slide3_main": "କୃଷକଙ୍କ ପାଇଁ।",
    "slide3_desc": "ଆପଣଙ୍କ ଜୀବିକା ପାଇଁ କୃଷି ସହାୟତା, ଆର୍ଥିକ ସାହାଯ୍ୟ ଏବଂ ଯୋଜନା ଖୋଜନ୍ତୁ।",
    "slide4_prefix": "ପ୍ରତ୍ୟେକ",
    "slide4_main": "ମହିଳାଙ୍କ ପାଇଁ।",
    "slide4_desc": "ଆପଣଙ୍କ ପ୍ରଗତି ପାଇଁ ସୁବିଧା, ଆର୍ଥିକ ସହାୟତା ଏବଂ ସୁଯୋଗ ଖୋଜନ୍ତୁ।",
    "slide5_prefix": "ପ୍ରତ୍ୟେକ",
    "slide5_main": "ଉଦ୍ୟୋଗୀଙ୍କ ପାଇଁ।",
    "slide5_desc": "ଆପଣଙ୍କ ବ୍ୟବସାୟ ପାଇଁ ବ୍ୟବସାୟ ସହାୟତା, ପ୍ରୋତ୍ସାହନ ଏବଂ ସରକାରୀ ଯୋଜନା ଖୋଜନ୍ତୁ।",
    "slide6_prefix": "ପ୍ରତ୍ୟେକ",
    "slide6_main": "ପିଢ଼ି ପାଇଁ।",
    "slide6_desc": "ଦୈନନ୍ଦିନ ଜୀବନକୁ ଅଧିକ ସୁରକ୍ଷିତ କରିବା ପାଇଁ ସହାୟତା ଏବଂ ଯୋଜନା ଖୋଜନ୍ତୁ।",
    "builtForEveryCitizen": "ପ୍ରତ୍ୟେକ ନାଗରିକଙ୍କ ପାଇଁ ନିର୍ମିତ",
    "govSchemes": "ସରକାରୀ ଯୋଜନା",
    "citizenServices": "ନାଗରିକ ସେବା",
    "digitalAccess": "ଡିଜିଟାଲ୍ ପ୍ରବେଶ",
    "businessSupport": "ବ୍ୟବସାୟ ସହାୟତା",
    "independentCitizenPlatform": "ସ୍ୱତନ୍ତ୍ର ନାଗରିକ ମଞ୍ଚ",
    "privacy": "ଗୋପନୀୟତା",
    "terms": "ସର୍ତ୍ତାବଳୀ",
    "platformDisclaimer": "ଯୋଜନା ସେତୁ ଏକ ସ୍ୱତନ୍ତ୍ର ପ୍ଲାଟଫର୍ମ ଯାହା ନାଗରିକମାନଙ୍କୁ ସରକାରୀ ଯୋଜନା ଖୋଜିବାରେ ସାହାଯ୍ୟ କରେ।",
    "allApplicationsSubtitle": "ସମସ୍ତ ବିଭାଗର ଆବେଦନଗୁଡ଼ିକର ସମୀକ୍ଷା ଏବଂ ପରିଚାଳନା କରନ୍ତୁ",
    "reviewLaterSubtitle": "ପରବର୍ତ୍ତୀ ମୂଲ୍ୟାଙ୍କନ ପାଇଁ ଧାଡ଼ିରେ ଥିବା ଆବେଦନ।",
    "schemeManagementSubtitle": "ସରକାରୀ କଲ୍ୟାଣକାରୀ ଯୋଜନା ଏବଂ ଯୋଗ୍ୟତା ପାରାମିଟର ପରିଚାଳନା କରନ୍ତୁ",
    "inReviewLaterQueue": "ପରବର୍ତ୍ତୀ ସମୀକ୍ଷା ଧାଡ଼ିରେ",
    "registeredJurisdiction": "ପଞ୍ଜୀକୃତ କ୍ଷେତ୍ରାଧିକାର",
    "directBenefit": "ପ୍ରତ୍ୟକ୍ଷ ଲାଭ",
    "schemeNotFound": "ଯୋଜନା ମିଳିଲା ନାହିଁ",
    "years": "ବର୍ଷ",
    "gender_male": "ପୁରୁଷ",
    "gender_female": "ମହିଳା",
    "gender_other": "ଅନ୍ୟାନ୍ୟ",
    "category_Agriculture": "କୃଷି",
    "category_Finance": "ବିତ୍ତ",
    "category_Healthcare": "ସ୍ୱାସ୍ଥ୍ୟସେବା",
    "category_Housing": "ଗୃହନିର୍ମାଣ",
    "category_Education": "ଶିକ୍ଷା",
    "status_pending": "ବିଚାରାଧୀନ",
    "status_in_review": "ସମୀକ୍ଷାଧୀନ",
    "status_approved": "ଅନୁମୋଦିତ",
    "status_rejected": "ପ୍ରତ୍ୟାଖ୍ୟାନ",
    "notifTitle_notif-1": "ପିଏମ-କିସାନ ଆବେଦନ ଅନୁମୋଦିତ",
    "notifTitle_notif_1": "ପିଏମ-କିସାନ ଆବେଦନ ଅନୁମୋଦିତ",
    "notifMsg_notif-1": "ଆପଣଙ୍କ ଆବେଦନ ସଫଳତାର ସହିତ ଯାଞ୍ଚ ହୋଇ ଅନୁମୋଦନ ଲାଭ କରିଛି।",
    "notifMsg_notif_1": "ଆପଣଙ୍କ ଆବେଦନ ସଫଳତାର ସହିତ ଯାଞ୍ଚ ହୋଇ ଅନୁମୋଦନ ଲାଭ କରିଛି।",
    "notifTitle_notif-2": "ନୂତନ ଯୋଗ୍ୟତା ମେଳ: ଆୟୁଷ୍ମାନ ଭାରତ",
    "notifTitle_notif_2": "ନୂତନ ଯୋଗ୍ୟତା ମେଳ: ଆୟୁଷ୍ମାନ ଭାରତ",
    "notifMsg_notif-2": "ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ଆଧାରରେ ଆପଣ ବର୍ତ୍ତମାନ ଆୟୁଷ୍ମାନ ଭାରତ ଯୋଜନା ପାଇଁ ଯୋଗ୍ୟ।",
    "notifMsg_notif_2": "ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ଆଧାରରେ ଆପଣ ବର୍ତ୍ତମାନ ଆୟୁଷ୍ମାନ ଭାରତ ଯୋଜନା ପାଇଁ ଯୋଗ୍ୟ।",
    "notifTitle_notif-3": "ଦସ୍ତାବିଜ ପ୍ରତ୍ୟାଖ୍ୟାନ: ଆୟ ପ୍ରମାଣପତ୍ର",
    "notifTitle_notif_3": "ଦସ୍ତାବିଜ ପ୍ରତ୍ୟାଖ୍ୟାନ: ଆୟ ପ୍ରମାଣପତ୍ର",
    "notifMsg_notif-3": "ପ୍ରଦାନ କରାଯାଇଥିବା ଆୟ ପ୍ରମାଣପତ୍ର ୬ ମାସରୁ ପୁରୁଣା। ଦୟାକରି ବୈଧ ଦସ୍ତାବିଜ ଅପଲୋଡ୍ କରନ୍ତୁ।",
    "notifMsg_notif_3": "ପ୍ରଦାନ କରାଯାଇଥିବା ଆୟ ପ୍ରମାଣପତ୍ର ୬ ମାସରୁ ପୁରୁଣା। ଦୟାକରି ବୈଧ ଦସ୍ତାବିଜ ଅପଲୋଡ୍ କରନ୍ତୁ।",
    "notifTitle_notif-4": "ସିଷ୍ଟମ୍ ରକ୍ଷଣାବେକ୍ଷଣ କାର୍ଯ୍ୟସୂଚୀ",
    "notifTitle_notif_4": "ସିଷ୍ଟମ୍ ରକ୍ଷଣାବେକ୍ଷଣ କାର୍ଯ୍ୟସୂଚୀ",
    "notifMsg_notif-4": "ରବିବାର ଭୋର ୨:୦୦ ରୁ ୬:୦୦ ପର୍ଯ୍ୟନ୍ତ ପୋର୍ଟାଲ୍ ରକ୍ଷଣାବେକ୍ଷଣ କରାଯିବ।",
    "notifMsg_notif_4": "ରବିବାର ଭୋର ୨:୦୦ ରୁ ୬:୦୦ ପର୍ଯ୍ୟନ୍ତ ପୋର୍ଟାଲ୍ ରକ୍ଷଣାବେକ୍ଷଣ କରାଯିବ।",
    "badge_approved": "ଅନୁମୋଦିତ",
    "badge_scheme_added": "ନୂତନ ଯୋଜନା",
    "badge_action_required": "କାର୍ଯ୍ୟାନୁଷ୍ଠାନ ଆବଶ୍ୟକ",
    "badge_info": "ଘୋଷଣା",
    "time_notif-1": "୨ ଘଣ୍ଟା ପୂର୍ବରୁ",
    "time_notif-2": "୫ ଘଣ୍ଟା ପୂର୍ବରୁ",
    "time_notif-3": "ଗତକାଲି, ଅପରାହ୍ନ ୨:୩୦",
    "time_notif-4": "ଗତକାଲି, ସକାଳ ୧୦:୧୫",
    "rejection_income_expired": "ପ୍ରଦାନ କରାଯାଇଥିବା ଆୟ ପ୍ରମାଣପତ୍ର ୬ ମାସରୁ ପୁରୁଣା। ବୈଧ ଦସ୍ତାବିଜ ସହିତ ପୁନର୍ବାର ଆବେଦନ କରନ୍ତୁ।",
    "rejection_ayushman-pmjay": "ପ୍ରଦାନ କରାଯାଇଥିବା ଆୟ ପ୍ରମାଣପତ୍ର ୬ ମାସରୁ ପୁରୁଣା। ବୈଧ ଦସ୍ତାବିଜ ସହିତ ପୁନର୍ବାର ଆବେଦନ କରନ୍ତୁ।",
    "rejection_general": "ପ୍ରଦାନ କରାଯାଇଥିବା ଆୟ ପ୍ରମାଣପତ୍ର ୬ ମାସରୁ ପୁରୁଣା। ବୈଧ ଦସ୍ତାବିଜ ସହିତ ପୁନର୍ବାର ଆବେଦନ କରନ୍ତୁ।",
    "timeline_application_submitted": "ଆବେଦନ ଦାଖଲ ହୋଇଛି",
    "timeline_document_verification": "ଦସ୍ତାବିଜ ଯାଞ୍ଚ",
    "timeline_application_approved": "ଆବେଦନ ଅନୁମୋଦିତ",
    "timeline_under_review": "ସମୀକ୍ଷାଧୀନ",
    "timeline_application_rejected": "ଆବେଦନ ପ୍ରତ୍ୟାଖ୍ୟାନ",
    "timeline_decision": "ନିଷ୍ପତ୍ତି",
    "timelineDesc_application_submitted": "ଆବେଦନ ଗ୍ରହଣ କରାଯାଇ ସମୀକ୍ଷା ଟିମକୁ ପଠାଗଲା।",
    "timelineDesc_document_verification": "ଦାଖଲ ହୋଇଥିବା ସମସ୍ତ ଦସ୍ତାବିଜ ଯାଞ୍ଚ ହେଲା।",
    "timelineDesc_application_approved": "ଆପଣଙ୍କ ଆବେଦନ ଅନୁମୋଦନ ଲାଭ କରିଛି। ସବସିଡି ରାଶି ଶୀଘ୍ର ପ୍ରଦାନ କରାଯିବ।",
    "timelineDesc_under_review": "ପ୍ରାଥମିକ ଯାଞ୍ଚ ଚାଲିଛି।",
    "timelineDesc_application_rejected": "ପ୍ରଦାନ କରାଯାଇଥିବା ଆୟ ପ୍ରମାଣପତ୍ର ୬ ମାସରୁ ପୁରୁଣା। ପୁନର୍ବାର ଆବେଦନ କରନ୍ତୁ।",
    "scheme_pm-kisan": "ପିଏମ-କିସାନ ସମ୍ମାନ ନିଧି",
    "scheme_pm-fby": "ପ୍ରଧାନମନ୍ତ୍ରୀ ଫସଲ ବୀମା ଯୋଜନା (PMFBY)",
    "scheme_mudra-shishu": "ମୁଦ୍ରା ଶିଶୁ ଋଣ",
    "scheme_pmay-urban": "ପ୍ରଧାନମନ୍ତ୍ରୀ ଆବାସ ଯୋଜନା (PMAY - ସହରାଞ୍ଚଳ)",
    "scheme_ayushman-pmjay": "ଆୟୁଷ୍ମାନ ଭାରତ PM-JAY",
    "scheme_standup-india": "ଷ୍ଟାଣ୍ଡ-ଅପ୍ ଇଣ୍ଡିଆ ଯୋଜନା",
    "scheme_national-scholarship": "ଜାତୀୟ ଛାତ୍ରବୃତ୍ତି ପୋର୍ଟାଲ୍ (NSP ମାଟ୍ରିକ ପରବର୍ତ୍ତୀ)",
    "scheme_udyam-msme-subsidy": "ଉଦ୍ୟମ MSME ପ୍ରଯୁକ୍ତିବିଦ୍ୟା ଏବଂ କ୍ରେଡିଟ୍ ସବସିଡି",
    "scheme_pm-svanidhi": "ପିଏମ ସ୍ୱନିଧି ଯୋଜନା",
    "scheme_pm-vishwakarma": "ପିଏମ ବିଶ୍ୱକର୍ମା କୌଶଳ ସମ୍ମାନ",
    "dept_pm-kisan": "କୃଷି ଏବଂ କୃଷକ କଲ୍ୟାଣ ମନ୍ତ୍ରଣାଳୟ",
    "dept_pm-fby": "କୃଷି ଏବଂ କୃଷକ କଲ୍ୟାଣ ମନ୍ତ୍ରଣାଳୟ",
    "dept_mudra-shishu": "ଅର୍ଥ ମନ୍ତ୍ରଣାଳୟ",
    "dept_pmay-urban": "ଗୃହ ଏବଂ ନଗର ଉନ୍ନୟନ ମନ୍ତ୍ରଣାଳୟ",
    "dept_ayushman-pmjay": "ଜାତୀୟ ସ୍ୱାସ୍ଥ୍ୟ ପ୍ରାଧିକରଣ",
    "dept_standup-india": "ଅର୍ଥ ମନ୍ତ୍ରଣାଳୟ",
    "dept_national-scholarship": "ସାମାଜିକ ନ୍ୟାୟ ଏବଂ ସଶକ୍ତୀକରଣ ମନ୍ତ୍ରଣାଳୟ",
    "dept_udyam-msme-subsidy": "ସୂକ୍ଷ୍ମ, କ୍ଷୁଦ୍ର ଏବଂ ମଧ୍ୟମ ଉଦ୍ୟୋଗ ମନ୍ତ୍ରଣାଳୟ",
    "dept_pm-svanidhi": "ଗୃହ ଏବଂ ନଗର ଉନ୍ନୟନ ମନ୍ତ୍ରଣାଳୟ",
    "dept_pm-vishwakarma": "MSME ମନ୍ତ୍ରଣାଳୟ",
    "benefit_pm-kisan": "₹୬,୦୦୦ / ବର୍ଷ",
    "benefit_pm-fby": "ଫସଲ ବୀମା",
    "benefit_mudra-shishu": "₹୫୦,୦୦୦ ପର୍ଯ୍ୟନ୍ତ",
    "benefit_pmay-urban": "₹୨.୬୭ ଲକ୍ଷ ପର୍ଯ୍ୟନ୍ତ ସବସିଡି",
    "benefit_ayushman-pmjay": "₹୫ ଲକ୍ଷ / ପରିବାର / ବର୍ଷ",
    "benefit_standup-india": "₹୧୦ ଲକ୍ଷ ରୁ ₹୧ କୋଟି",
    "benefit_national-scholarship": "₹୫୦,୦୦୦ / ବର୍ଷ ପର୍ଯ୍ୟନ୍ତ",
    "benefit_udyam-msme-subsidy": "୧୫% ପୁଞ୍ଜି ସବସିଡି",
    "benefit_pm-svanidhi": "₹୫୦,୦୦୦ ପର୍ଯ୍ୟନ୍ତ",
    "benefit_pm-vishwakarma": "₹୧୫,୦୦୦ ଟୁଲକିଟ୍ + ଋଣ",
    "benefitDetail_pm-kisan": "ପ୍ରତ୍ୟକ୍ଷ ଲାଭ ହସ୍ତାନ୍ତର (DBT)",
    "benefitDetail_pm-fby": "₹୨ ଲକ୍ଷ ପର୍ଯ୍ୟନ୍ତ କଭରେଜ୍",
    "benefitDetail_mudra-shishu": "ବିନା ବନ୍ଧକ ଋଣ",
    "benefitDetail_pmay-urban": "ସୁଧ ସବସିଡି ଯୋଜନା",
    "benefitDetail_ayushman-pmjay": "କ୍ୟାସଲେସ୍ ସ୍ୱାସ୍ଥ୍ୟ କଭର",
    "benefitDetail_standup-india": "ଗ୍ରୀନଫିଲ୍ଡ ଏଣ୍ଟରପ୍ରାଇଜ୍ ଋଣ",
    "benefitDetail_national-scholarship": "ଶିକ୍ଷା ଦେୟ + ଷ୍ଟାଇପେଣ୍ଡ",
    "benefitDetail_udyam-msme-subsidy": "ପ୍ରଯୁକ୍ତିବିଦ୍ୟା ନବୀକରଣ ପାଇଁ ₹୧୫ ଲକ୍ଷ ପର୍ଯ୍ୟନ୍ତ",
    "benefitDetail_pm-svanidhi": "୭% ସୁଧ ସବସିଡି",
    "benefitDetail_pm-vishwakarma": "୫% ସୁଧରେ ₹୩ ଲକ୍ଷ ପର୍ଯ୍ୟନ୍ତ",
    "deadline_pm-kisan": "୧୫ ଦିନରେ ବନ୍ଦ ହେବ",
    "deadline_pm-fby": "୩୦ ସେପ୍ଟେମ୍ବର ୨୦୨୬ ରେ ଶେଷ",
    "deadline_mudra-shishu": "ସର୍ବଦା ଖୋଲା",
    "deadline_pmay-urban": "୩୧ ଡିସେମ୍ବର ୨୦୨୬ ରେ ଶେଷ",
    "deadline_ayushman-pmjay": "ସର୍ବଦା ଖୋଲା",
    "deadline_standup-india": "୩୦ ନଭେମ୍ବର ୨୦୨୬ ରେ ଶେଷ",
    "deadline_national-scholarship": "୧୫ ଅକ୍ଟୋବର ୨୦୨୬ ରେ ଶେଷ",
    "deadline_udyam-msme-subsidy": "୩୧ ଅକ୍ଟୋବର ୨୦୨୬ ରେ ଶେଷ",
    "deadline_pm-svanidhi": "ସର୍ବଦା ଖୋଲା",
    "deadline_pm-vishwakarma": "୧୫ ନଭେମ୍ବର ୨୦୨୬ ରେ ଶେଷ",
    "desc_pm-kisan": "ଦେଶର ସମସ୍ତ ଚାଷୀ ପରିବାରକୁ ଆର୍ଥିକ ସହାୟତା ପ୍ରଦାନ କରିବା ପାଇଁ ଏକ କେନ୍ଦ୍ରୀୟ ଯୋଜନା।",
    "desc_pm-fby": "ପ୍ରାକୃତିକ ବିପର୍ଯ୍ୟୟ କାରଣରୁ ଫସଲ ନଷ୍ଟ ହେଲେ ଚାଷୀଙ୍କୁ ସହାୟତା ପ୍ରଦାନ କରୁଥିବା ବୀମା ଯୋଜନା।",
    "desc_mudra-shishu": "କ୍ଷୁଦ୍ର ଉଦ୍ୟୋଗ ପାଇଁ ₹୫୦,୦୦୦ ପର୍ଯ୍ୟନ୍ତ ବିନା ବନ୍ଧକ ସଂସ୍ଥାଗତ ଋଣ।",
    "desc_pmay-urban": "ସହରାଞ୍ଚଳରେ ଆର୍ଥିକ ଦୁର୍ବଳ ବର୍ଗଙ୍କୁ ଘର ନିର୍ମାଣ ପାଇଁ ସବସିଡି ଯୋଜନା।",
    "desc_ayushman-pmjay": "ମାଗଣା ଚିକିତ୍ସା ପାଇଁ ବିଶ୍ୱର ସର୍ବବୃହତ ସରକାରୀ ସ୍ୱାସ୍ଥ୍ୟ ସୁରକ୍ଷା ଯୋଜନା।",
    "desc_standup-india": "ଏସସି/ଏସଟି ଏବଂ ମହିଳା ଉଦ୍ୟୋଗୀମାନଙ୍କୁ ନୂତନ ବ୍ୟବସାୟ ପାଇଁ ₹୧୦ ଲକ୍ଷରୁ ₹୧ କୋଟି ଋଣ।",
    "desc_national-scholarship": "ମେଧାବୀ ଛାତ୍ରଛାତ୍ରୀଙ୍କ ଉଚ୍ଚଶିକ୍ଷା ପାଇଁ ଆର୍ଥିକ ସହାୟତା।",
    "desc_udyam-msme-subsidy": "ପଞ୍ଜୀକୃତ MSME ପାଇଁ ପୁଞ୍ଜି ବିନିଯୋଗ ଏବଂ ପ୍ରଯୁକ୍ତିବିଦ୍ୟା ନବୀକରଣ ସବସିଡି।",
    "desc_pm-svanidhi": "ଉଠାଦୋକାନୀମାନଙ୍କ ପାଇଁ ₹୫୦,୦୦୦ ପର୍ଯ୍ୟନ୍ତ କାର୍ଯ୍ୟକାରୀ ପୁଞ୍ଜି ଋଣ ସୁବିଧା।",
    "desc_pm-vishwakarma": "ପାରମ୍ପରିକ କାରିଗର ଏବଂ ଶିଳ୍ପୀମାନଙ୍କ ପାଇଁ ତାଲିମ, ଟୁଲକିଟ୍ ଏବଂ ଋଣ ସହାୟତା।",
    "overview_pm-kisan": "ପିଏମ-କିସାନ ଯୋଜନା ଅଧୀନରେ ଚାଷୀ ପରିବାରକୁ ବାର୍ଷିକ ₹୬,୦୦୦ ତିନୋଟି ସମାନ କିସ୍ତିରେ ସିଧାସଳଖ ବ୍ୟାଙ୍କ ଖାତାକୁ ପ୍ରଦାନ କରାଯାଏ।",
    "overview_pm-fby": "PMFBY ଖାଦ୍ୟ ଏବଂ ତୈଳବୀଜ ଫସଲ ପାଇଁ ପ୍ରାକୃତିକ ବିପଦରୁ ସମ୍ପୂର୍ଣ୍ଣ ବୀମା କଭର ପ୍ରଦାନ କରେ।",
    "overview_mudra-shishu": "କ୍ଷୁଦ୍ର ଉତ୍ପାଦନ ୟୁନିଟ୍, ଦୋକାନୀ ଏବଂ କାରିଗରଙ୍କୁ ₹୫୦,୦୦୦ ପର୍ଯ୍ୟନ୍ତ ଋଣ ପ୍ରଦାନ କରାଯାଏ।",
    "overview_pmay-urban": "ଯୋଗ୍ୟ ସହରୀ ପରିବାରଙ୍କୁ ଗୃହ ଋଣ ଉପରେ ସୁଧ ସବସିଡି ପ୍ରଦାନ କରେ।",
    "overview_ayushman-pmjay": "ସରକାରୀ ଏବଂ ତାଲିକାଭୁକ୍ତ ଘରୋଇ ଡାକ୍ତରଖାନାରେ ପ୍ରତି ପରିବାରକୁ ବାର୍ଷିକ ₹୫ ଲକ୍ଷ ପର୍ଯ୍ୟନ୍ତ ସ୍ୱାସ୍ଥ୍ୟ କଭର ପ୍ରଦାନ କରେ।",
    "overview_standup-india": "ଉତ୍ପାଦନ, ସେବା କିମ୍ବା ବାଣିଜ୍ୟ କ୍ଷେତ୍ରରେ ନୂତନ ଉଦ୍ୟୋଗ ପ୍ରତିଷ୍ଠା ପାଇଁ ବ୍ୟାଙ୍କ ଋଣ ସୁଗମ କରେ।",
    "overview_national-scholarship": "ଯୋଗ୍ୟ ଛାତ୍ରଛାତ୍ରୀଙ୍କ ବ୍ୟାଙ୍କ ଖାତାକୁ ସିଧାସଳଖ ଫିସ୍ ଏବଂ ବହି ଅନୁଦାନ ପ୍ରଦାନ କରେ।",
    "overview_udyam-msme-subsidy": "ଉନ୍ନତ ପ୍ରଯୁକ୍ତିବିଦ୍ୟା ଆପଣାଇବା ପାଇଁ ୧୫% ପର୍ଯ୍ୟନ୍ତ ଅଗ୍ରୀମ ପୁଞ୍ଜି ସବସିଡି ପ୍ରଦାନ କରେ।",
    "overview_pm-svanidhi": "ଉଠାଦୋକାନୀମାନଙ୍କୁ ସୁଧ ସବସିଡି ଏବଂ ଡିଜିଟାଲ୍ ପ୍ରୋତ୍ସାହନ ସହିତ ଋଣ ପ୍ରଦାନ କରେ।",
    "overview_pm-vishwakarma": "ବିଶ୍ୱକର୍ମା ପ୍ରମାଣପତ୍ର, ଷ୍ଟାଇପେଣ୍ଡ ସହିତ ତାଲିମ, ₹୧୫,୦୦୦ ଟୁଲକିଟ୍ ଅନୁଦାନ ଏବଂ ୫% ସୁଧରେ ଋଣ ପ୍ରଦାନ କରେ।"
}

# Merge all into mr and od
for k, v in MR_OVERRIDES.items():
    mr[k] = v

for k, v in OR_OVERRIDES.items():
    od[k] = v

with open(os.path.join(TRANSLATIONS_DIR, "mr.json"), "w", encoding="utf-8") as f:
    json.dump(mr, f, ensure_ascii=False, indent=2)

with open(os.path.join(TRANSLATIONS_DIR, "or.json"), "w", encoding="utf-8") as f:
    json.dump(od, f, ensure_ascii=False, indent=2)

print("Enriched mr.json and or.json successfully!")
